### PR TITLE
[ISS-141] Fix black, isort and flake8 config to work together in one project

### LINKED ISSUE #141: Fix black, isort and flake8 configurations
Flake8 and isort has to have special configuration flag to work with black in one project. Otherwise black return error after fixes from isort and flake8

### PR DESCRIPTION
**Pull request by jlatusek**
Fix #141

### CODE REVIEW

**Comment by Hamilkar247** [comment]
Please add prefix [ISS-141] to names of commits

**Comment by Hamilkar247** [comment]
@jlatusek

**Comment by Hamilkar247** [comment]
@jlatusek Please add prefix [ISS-141] to names of commits

**Comment by jlatusek** [comment]
@Hamilkar247 prefixs fixed

**Pull request merged**
