### PR TITLE
ISS-81 port-POSTGRES_DB 5432:5432 --> 5431:5432

### PR DESCRIPTION
**Pull request by Hamilkar247**
Signed-off-by: Hamilkar247 <adonnibal96@gmail.com>

### CODE REVIEW

**Comment by jlatusek** [comment]
Hardcoded value isn't way that this supposed to be resolved.

**Comment by Hamilkar247** [comment]
it is only to a moment when you finish your update to docker postgres

**Comment by jlatusek** [comment]
so keep your local config, and don't create something unnecessary, this will only lead to merge conflict in the future.

**Comment by jlatusek** [comment]
merge #83

**Comment by Hamilkar247** [comment]
ok

**Pull request closed without merging**
